# Generated by Django 2.0.4 on 2018-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('groupId', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login_ip', models.CharField(max_length=255)),
                ('last_login_time', models.DateTimeField()),
                ('department', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('realname', models.CharField(max_length=255)),
            ],
        ),
    ]
